### ISSUE TITLE
Move property to the top

### ISSUE THREAD

**Issue by Bad3r** [yoyurec/logseq-awesome-props#17]
Is it possible to move the property to the top instead of being centered?
![image](https://user-images.githubusercontent.com/25513724/229320023-b5c9aac1-2d71-4460-854c-0929d6c856ae.png)

**Comment by Bad3r** [comment]
nvm can be changed with:
```css
.block-properties > div > div {
    display: inline-flex !important;
    align-items: flex-start;
}
```
