### ISSUE TITLE
Feature request: Inline props

### ISSUE THREAD

**Issue by Zachu** [yoyurec/logseq-awesome-props#3]
**Idea**
Instead of having a "description list" styled properties I would very much like to have inline properties as an toggleable feature. This feature alone has been the reason I haven't been able to enjoy the cool feature of these icons. 

**Other stuff**

I have previously done the inline in a `custom.css` with following snippet which you are of course free to use if you want to. Although I bet your CSS-fu is much better than mine is 😅 I just hacked something together that works for me:
```css
.content .block-properties {
  display: flex;
  flex-wrap: wrap;
  white-space: nowrap;
  overflow: hidden;
  font-size: 0.8em;
  border-radius: 8px;
  box-shadow: 0 0 0 2px var(--color-level-2);
  background-color: var(--color-level-1);
  margin: 0 0 0 1rem;
  padding: 2px 5px;
}
.block-properties > div:first-child:before {
  content: "🏷";
  #color: rgba(255, 255, 0, 0.5);
  font-weight: bold;
  margin-right: 0.25rem;
}
.block-properties > div:last-child:after {
  content: "";
}
.block-properties > div:after {
  content: ", ";
  margin-right: 0.25rem;
}
.block-properties div.inline {
  margin-right: 0;
}
```

Quite recently I ran across a simpler one in this [Discord comment](https://discord.com/channels/725182569297215569/752845138148982877/1074463439860285522):
```css
.block-properties {
  margin-top: 4px;
  padding: 0.1rem 0.5rem;
  display: flex;
  flex-wrap: wrap;
  column-gap: 6px;
  border: 1.5px solid #464650;
  max-width: fit-content;
  vertical-align: middle;
  border-radius: 6px;
}
```

Neither of these currently work with the Awesome Props. Personally I don't prefer either over one =)

**Screenshots**
Here's how things look in my Logseq atm:

With the older CSS solution:
![image](https://user-images.githubusercontent.com/1262488/219596714-5b8ab5b7-5841-4615-b5a6-5d83a1694787.png)

With the simpler one:
![image](https://user-images.githubusercontent.com/1262488/219596453-430db260-f587-4eb3-a270-6fe6c30dcd4a.png)

**Attach files**

Block for the screenshots:
```md
- ## This is some block  
  url:: https://example.com
  icon:: 👍
  type:: Task
  project:: [[A project]]
  people:: [[Some person]]
	- Something here...  
```
